/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SharedStructs {
  export type ResultStruct = {
    dealId: string;
    resultsId: string;
    dataId: string;
    instructionCount: BigNumberish;
  };

  export type ResultStructOutput = [
    dealId: string,
    resultsId: string,
    dataId: string,
    instructionCount: bigint
  ] & {
    dealId: string;
    resultsId: string;
    dataId: string;
    instructionCount: bigint;
  };

  export type AgreementStruct = {
    state: BigNumberish;
    resourceProviderAgreedAt: BigNumberish;
    jobCreatorAgreedAt: BigNumberish;
    dealCreatedAt: BigNumberish;
    dealAgreedAt: BigNumberish;
    resultsSubmittedAt: BigNumberish;
    resultsAcceptedAt: BigNumberish;
    resultsCheckedAt: BigNumberish;
    mediationAcceptedAt: BigNumberish;
    mediationRejectedAt: BigNumberish;
    timeoutAgreeAt: BigNumberish;
    timeoutSubmitResultsAt: BigNumberish;
    timeoutJudgeResultsAt: BigNumberish;
    timeoutMediateResultsAt: BigNumberish;
  };

  export type AgreementStructOutput = [
    state: bigint,
    resourceProviderAgreedAt: bigint,
    jobCreatorAgreedAt: bigint,
    dealCreatedAt: bigint,
    dealAgreedAt: bigint,
    resultsSubmittedAt: bigint,
    resultsAcceptedAt: bigint,
    resultsCheckedAt: bigint,
    mediationAcceptedAt: bigint,
    mediationRejectedAt: bigint,
    timeoutAgreeAt: bigint,
    timeoutSubmitResultsAt: bigint,
    timeoutJudgeResultsAt: bigint,
    timeoutMediateResultsAt: bigint
  ] & {
    state: bigint;
    resourceProviderAgreedAt: bigint;
    jobCreatorAgreedAt: bigint;
    dealCreatedAt: bigint;
    dealAgreedAt: bigint;
    resultsSubmittedAt: bigint;
    resultsAcceptedAt: bigint;
    resultsCheckedAt: bigint;
    mediationAcceptedAt: bigint;
    mediationRejectedAt: bigint;
    timeoutAgreeAt: bigint;
    timeoutSubmitResultsAt: bigint;
    timeoutJudgeResultsAt: bigint;
    timeoutMediateResultsAt: bigint;
  };

  export type DealMembersStruct = {
    solver: AddressLike;
    jobCreator: AddressLike;
    resourceProvider: AddressLike;
    mediators: AddressLike[];
  };

  export type DealMembersStructOutput = [
    solver: string,
    jobCreator: string,
    resourceProvider: string,
    mediators: string[]
  ] & {
    solver: string;
    jobCreator: string;
    resourceProvider: string;
    mediators: string[];
  };

  export type DealTimeoutStruct = {
    timeout: BigNumberish;
    collateral: BigNumberish;
  };

  export type DealTimeoutStructOutput = [
    timeout: bigint,
    collateral: bigint
  ] & { timeout: bigint; collateral: bigint };

  export type DealTimeoutsStruct = {
    agree: SharedStructs.DealTimeoutStruct;
    submitResults: SharedStructs.DealTimeoutStruct;
    judgeResults: SharedStructs.DealTimeoutStruct;
    mediateResults: SharedStructs.DealTimeoutStruct;
  };

  export type DealTimeoutsStructOutput = [
    agree: SharedStructs.DealTimeoutStructOutput,
    submitResults: SharedStructs.DealTimeoutStructOutput,
    judgeResults: SharedStructs.DealTimeoutStructOutput,
    mediateResults: SharedStructs.DealTimeoutStructOutput
  ] & {
    agree: SharedStructs.DealTimeoutStructOutput;
    submitResults: SharedStructs.DealTimeoutStructOutput;
    judgeResults: SharedStructs.DealTimeoutStructOutput;
    mediateResults: SharedStructs.DealTimeoutStructOutput;
  };

  export type DealPricingStruct = {
    instructionPrice: BigNumberish;
    paymentCollateral: BigNumberish;
    resultsCollateralMultiple: BigNumberish;
    mediationFee: BigNumberish;
  };

  export type DealPricingStructOutput = [
    instructionPrice: bigint,
    paymentCollateral: bigint,
    resultsCollateralMultiple: bigint,
    mediationFee: bigint
  ] & {
    instructionPrice: bigint;
    paymentCollateral: bigint;
    resultsCollateralMultiple: bigint;
    mediationFee: bigint;
  };

  export type DealStruct = {
    dealId: string;
    members: SharedStructs.DealMembersStruct;
    timeouts: SharedStructs.DealTimeoutsStruct;
    pricing: SharedStructs.DealPricingStruct;
  };

  export type DealStructOutput = [
    dealId: string,
    members: SharedStructs.DealMembersStructOutput,
    timeouts: SharedStructs.DealTimeoutsStructOutput,
    pricing: SharedStructs.DealPricingStructOutput
  ] & {
    dealId: string;
    members: SharedStructs.DealMembersStructOutput;
    timeouts: SharedStructs.DealTimeoutsStructOutput;
    pricing: SharedStructs.DealPricingStructOutput;
  };
}

export interface HiveStorageTestableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptResult"
      | "addResult"
      | "agreeJobCreator"
      | "agreeResourceProvider"
      | "checkResult"
      | "disableChangeControllerAddress"
      | "ensureDeal"
      | "getAgreement"
      | "getControllerAddress"
      | "getDeal"
      | "getDealsForParty"
      | "getJobCost"
      | "getResult"
      | "getResultsCollateral"
      | "hasDeal"
      | "initialize"
      | "isState"
      | "mediationAcceptResult"
      | "mediationRejectResult"
      | "owner"
      | "renounceOwnership"
      | "setControllerAddress"
      | "timeoutAgree"
      | "timeoutJudgeResult"
      | "timeoutMediateResult"
      | "timeoutSubmitResult"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DealStateChange"
      | "Initialized"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addResult",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agreeJobCreator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "agreeResourceProvider",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "checkResult", values: [string]): string;
  encodeFunctionData(
    functionFragment: "disableChangeControllerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ensureDeal",
    values: [
      string,
      SharedStructs.DealMembersStruct,
      SharedStructs.DealTimeoutsStruct,
      SharedStructs.DealPricingStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreement",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getControllerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getDeal", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getDealsForParty",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getJobCost", values: [string]): string;
  encodeFunctionData(functionFragment: "getResult", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getResultsCollateral",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "hasDeal", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isState",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mediationAcceptResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mediationRejectResult",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setControllerAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutAgree",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutJudgeResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutMediateResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutSubmitResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agreeJobCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agreeResourceProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableChangeControllerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ensureDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getControllerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDealsForParty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJobCost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getResultsCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mediationAcceptResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mediationRejectResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setControllerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutAgree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutJudgeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutMediateResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutSubmitResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DealStateChangeEvent {
  export type InputTuple = [dealId: string, state: BigNumberish];
  export type OutputTuple = [dealId: string, state: bigint];
  export interface OutputObject {
    dealId: string;
    state: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HiveStorageTestable extends BaseContract {
  connect(runner?: ContractRunner | null): HiveStorageTestable;
  waitForDeployment(): Promise<this>;

  interface: HiveStorageTestableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptResult: TypedContractMethod<[dealId: string], [void], "nonpayable">;

  addResult: TypedContractMethod<
    [
      dealId: string,
      resultsId: string,
      dataId: string,
      instructionCount: BigNumberish
    ],
    [SharedStructs.ResultStructOutput],
    "nonpayable"
  >;

  agreeJobCreator: TypedContractMethod<
    [dealId: string],
    [SharedStructs.AgreementStructOutput],
    "nonpayable"
  >;

  agreeResourceProvider: TypedContractMethod<
    [dealId: string],
    [SharedStructs.AgreementStructOutput],
    "nonpayable"
  >;

  checkResult: TypedContractMethod<[dealId: string], [void], "nonpayable">;

  disableChangeControllerAddress: TypedContractMethod<[], [void], "nonpayable">;

  ensureDeal: TypedContractMethod<
    [
      dealId: string,
      members: SharedStructs.DealMembersStruct,
      timeouts: SharedStructs.DealTimeoutsStruct,
      pricing: SharedStructs.DealPricingStruct
    ],
    [SharedStructs.DealStructOutput],
    "nonpayable"
  >;

  getAgreement: TypedContractMethod<
    [dealId: string],
    [SharedStructs.AgreementStructOutput],
    "view"
  >;

  getControllerAddress: TypedContractMethod<[], [string], "view">;

  getDeal: TypedContractMethod<
    [dealId: string],
    [SharedStructs.DealStructOutput],
    "view"
  >;

  getDealsForParty: TypedContractMethod<
    [party: AddressLike],
    [string[]],
    "view"
  >;

  getJobCost: TypedContractMethod<[dealId: string], [bigint], "view">;

  getResult: TypedContractMethod<
    [dealId: string],
    [SharedStructs.ResultStructOutput],
    "view"
  >;

  getResultsCollateral: TypedContractMethod<[dealId: string], [bigint], "view">;

  hasDeal: TypedContractMethod<[dealId: string], [boolean], "view">;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  isState: TypedContractMethod<
    [dealId: string, state: BigNumberish],
    [boolean],
    "view"
  >;

  mediationAcceptResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  mediationRejectResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setControllerAddress: TypedContractMethod<
    [_controllerAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  timeoutAgree: TypedContractMethod<[dealId: string], [void], "nonpayable">;

  timeoutJudgeResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  timeoutMediateResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  timeoutSubmitResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addResult"
  ): TypedContractMethod<
    [
      dealId: string,
      resultsId: string,
      dataId: string,
      instructionCount: BigNumberish
    ],
    [SharedStructs.ResultStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agreeJobCreator"
  ): TypedContractMethod<
    [dealId: string],
    [SharedStructs.AgreementStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agreeResourceProvider"
  ): TypedContractMethod<
    [dealId: string],
    [SharedStructs.AgreementStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disableChangeControllerAddress"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ensureDeal"
  ): TypedContractMethod<
    [
      dealId: string,
      members: SharedStructs.DealMembersStruct,
      timeouts: SharedStructs.DealTimeoutsStruct,
      pricing: SharedStructs.DealPricingStruct
    ],
    [SharedStructs.DealStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgreement"
  ): TypedContractMethod<
    [dealId: string],
    [SharedStructs.AgreementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getControllerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDeal"
  ): TypedContractMethod<
    [dealId: string],
    [SharedStructs.DealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDealsForParty"
  ): TypedContractMethod<[party: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getJobCost"
  ): TypedContractMethod<[dealId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [dealId: string],
    [SharedStructs.ResultStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResultsCollateral"
  ): TypedContractMethod<[dealId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasDeal"
  ): TypedContractMethod<[dealId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isState"
  ): TypedContractMethod<
    [dealId: string, state: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mediationAcceptResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mediationRejectResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setControllerAddress"
  ): TypedContractMethod<
    [_controllerAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timeoutAgree"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeoutJudgeResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeoutMediateResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeoutSubmitResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DealStateChange"
  ): TypedContractEvent<
    DealStateChangeEvent.InputTuple,
    DealStateChangeEvent.OutputTuple,
    DealStateChangeEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DealStateChange(string,uint8)": TypedContractEvent<
      DealStateChangeEvent.InputTuple,
      DealStateChangeEvent.OutputTuple,
      DealStateChangeEvent.OutputObject
    >;
    DealStateChange: TypedContractEvent<
      DealStateChangeEvent.InputTuple,
      DealStateChangeEvent.OutputTuple,
      DealStateChangeEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
