/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IHiveJobManagerInterface extends Interface {
  getFunction(nameOrSignature: "runJob" | "submitResults"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "runJob",
    values: [string, string[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResults",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "runJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitResults",
    data: BytesLike
  ): Result;
}

export interface IHiveJobManager extends BaseContract {
  connect(runner?: ContractRunner | null): IHiveJobManager;
  waitForDeployment(): Promise<this>;

  interface: IHiveJobManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  runJob: TypedContractMethod<
    [module: string, inputs: string[], payee: AddressLike],
    [bigint],
    "nonpayable"
  >;

  submitResults: TypedContractMethod<
    [id: BigNumberish, dealId: string, dataId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "runJob"
  ): TypedContractMethod<
    [module: string, inputs: string[], payee: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitResults"
  ): TypedContractMethod<
    [id: BigNumberish, dealId: string, dataId: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
