/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SharedStructs {
  export type DealMembersStruct = {
    solver: AddressLike;
    jobCreator: AddressLike;
    resourceProvider: AddressLike;
    mediators: AddressLike[];
  };

  export type DealMembersStructOutput = [
    solver: string,
    jobCreator: string,
    resourceProvider: string,
    mediators: string[]
  ] & {
    solver: string;
    jobCreator: string;
    resourceProvider: string;
    mediators: string[];
  };

  export type DealTimeoutStruct = {
    timeout: BigNumberish;
    collateral: BigNumberish;
  };

  export type DealTimeoutStructOutput = [
    timeout: bigint,
    collateral: bigint
  ] & { timeout: bigint; collateral: bigint };

  export type DealTimeoutsStruct = {
    agree: SharedStructs.DealTimeoutStruct;
    submitResults: SharedStructs.DealTimeoutStruct;
    judgeResults: SharedStructs.DealTimeoutStruct;
    mediateResults: SharedStructs.DealTimeoutStruct;
  };

  export type DealTimeoutsStructOutput = [
    agree: SharedStructs.DealTimeoutStructOutput,
    submitResults: SharedStructs.DealTimeoutStructOutput,
    judgeResults: SharedStructs.DealTimeoutStructOutput,
    mediateResults: SharedStructs.DealTimeoutStructOutput
  ] & {
    agree: SharedStructs.DealTimeoutStructOutput;
    submitResults: SharedStructs.DealTimeoutStructOutput;
    judgeResults: SharedStructs.DealTimeoutStructOutput;
    mediateResults: SharedStructs.DealTimeoutStructOutput;
  };

  export type DealPricingStruct = {
    instructionPrice: BigNumberish;
    paymentCollateral: BigNumberish;
    resultsCollateralMultiple: BigNumberish;
    mediationFee: BigNumberish;
  };

  export type DealPricingStructOutput = [
    instructionPrice: bigint,
    paymentCollateral: bigint,
    resultsCollateralMultiple: bigint,
    mediationFee: bigint
  ] & {
    instructionPrice: bigint;
    paymentCollateral: bigint;
    resultsCollateralMultiple: bigint;
    mediationFee: bigint;
  };

  export type AgreementStruct = {
    state: BigNumberish;
    resourceProviderAgreedAt: BigNumberish;
    jobCreatorAgreedAt: BigNumberish;
    dealCreatedAt: BigNumberish;
    dealAgreedAt: BigNumberish;
    resultsSubmittedAt: BigNumberish;
    resultsAcceptedAt: BigNumberish;
    resultsCheckedAt: BigNumberish;
    mediationAcceptedAt: BigNumberish;
    mediationRejectedAt: BigNumberish;
    timeoutAgreeAt: BigNumberish;
    timeoutSubmitResultsAt: BigNumberish;
    timeoutJudgeResultsAt: BigNumberish;
    timeoutMediateResultsAt: BigNumberish;
  };

  export type AgreementStructOutput = [
    state: bigint,
    resourceProviderAgreedAt: bigint,
    jobCreatorAgreedAt: bigint,
    dealCreatedAt: bigint,
    dealAgreedAt: bigint,
    resultsSubmittedAt: bigint,
    resultsAcceptedAt: bigint,
    resultsCheckedAt: bigint,
    mediationAcceptedAt: bigint,
    mediationRejectedAt: bigint,
    timeoutAgreeAt: bigint,
    timeoutSubmitResultsAt: bigint,
    timeoutJudgeResultsAt: bigint,
    timeoutMediateResultsAt: bigint
  ] & {
    state: bigint;
    resourceProviderAgreedAt: bigint;
    jobCreatorAgreedAt: bigint;
    dealCreatedAt: bigint;
    dealAgreedAt: bigint;
    resultsSubmittedAt: bigint;
    resultsAcceptedAt: bigint;
    resultsCheckedAt: bigint;
    mediationAcceptedAt: bigint;
    mediationRejectedAt: bigint;
    timeoutAgreeAt: bigint;
    timeoutSubmitResultsAt: bigint;
    timeoutJudgeResultsAt: bigint;
    timeoutMediateResultsAt: bigint;
  };
}

export interface IHiveControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptResult"
      | "addResult"
      | "agree"
      | "checkResult"
      | "mediationAcceptResult"
      | "mediationRejectResult"
      | "timeoutAgree"
      | "timeoutJudgeResult"
      | "timeoutMediateResult"
      | "timeoutSubmitResult"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addResult",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agree",
    values: [
      string,
      SharedStructs.DealMembersStruct,
      SharedStructs.DealTimeoutsStruct,
      SharedStructs.DealPricingStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "checkResult", values: [string]): string;
  encodeFunctionData(
    functionFragment: "mediationAcceptResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mediationRejectResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutAgree",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutJudgeResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutMediateResult",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutSubmitResult",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addResult", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agree", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mediationAcceptResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mediationRejectResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutAgree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutJudgeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutMediateResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutSubmitResult",
    data: BytesLike
  ): Result;
}

export interface IHiveController extends BaseContract {
  connect(runner?: ContractRunner | null): IHiveController;
  waitForDeployment(): Promise<this>;

  interface: IHiveControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptResult: TypedContractMethod<[dealId: string], [void], "nonpayable">;

  addResult: TypedContractMethod<
    [
      dealId: string,
      resultsId: string,
      dataId: string,
      instructionCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  agree: TypedContractMethod<
    [
      dealId: string,
      members: SharedStructs.DealMembersStruct,
      timeouts: SharedStructs.DealTimeoutsStruct,
      pricing: SharedStructs.DealPricingStruct
    ],
    [SharedStructs.AgreementStructOutput],
    "nonpayable"
  >;

  checkResult: TypedContractMethod<[dealId: string], [void], "nonpayable">;

  mediationAcceptResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  mediationRejectResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  timeoutAgree: TypedContractMethod<[dealId: string], [void], "nonpayable">;

  timeoutJudgeResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  timeoutMediateResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  timeoutSubmitResult: TypedContractMethod<
    [dealId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addResult"
  ): TypedContractMethod<
    [
      dealId: string,
      resultsId: string,
      dataId: string,
      instructionCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agree"
  ): TypedContractMethod<
    [
      dealId: string,
      members: SharedStructs.DealMembersStruct,
      timeouts: SharedStructs.DealTimeoutsStruct,
      pricing: SharedStructs.DealPricingStruct
    ],
    [SharedStructs.AgreementStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mediationAcceptResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mediationRejectResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeoutAgree"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeoutJudgeResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeoutMediateResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeoutSubmitResult"
  ): TypedContractMethod<[dealId: string], [void], "nonpayable">;

  filters: {};
}
