/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHiveJobManager,
  IHiveJobManagerInterface,
} from "../../contracts/IHiveJobManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "module",
        type: "string",
      },
      {
        internalType: "string[]",
        name: "inputs",
        type: "string[]",
      },
      {
        internalType: "address",
        name: "payee",
        type: "address",
      },
    ],
    name: "runJob",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "dealId",
        type: "string",
      },
      {
        internalType: "string",
        name: "dataId",
        type: "string",
      },
    ],
    name: "submitResults",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHiveJobManager__factory {
  static readonly abi = _abi;
  static createInterface(): IHiveJobManagerInterface {
    return new Interface(_abi) as IHiveJobManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHiveJobManager {
    return new Contract(address, _abi, runner) as unknown as IHiveJobManager;
  }
}
