/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHiveJobClient,
  IHiveJobClientInterface,
} from "../../contracts/IHiveJobClient";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "dealId",
        type: "string",
      },
      {
        internalType: "string",
        name: "dataId",
        type: "string",
      },
    ],
    name: "submitResults",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHiveJobClient__factory {
  static readonly abi = _abi;
  static createInterface(): IHiveJobClientInterface {
    return new Interface(_abi) as IHiveJobClientInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHiveJobClient {
    return new Contract(address, _abi, runner) as unknown as IHiveJobClient;
  }
}
