/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace SharedStructs {
  export type DealMembersStruct = {
    solver: AddressLike;
    jobCreator: AddressLike;
    resourceProvider: AddressLike;
    mediators: AddressLike[];
  };

  export type DealMembersStructOutput = [
    solver: string,
    jobCreator: string,
    resourceProvider: string,
    mediators: string[]
  ] & {
    solver: string;
    jobCreator: string;
    resourceProvider: string;
    mediators: string[];
  };

  export type DealTimeoutStruct = {
    timeout: BigNumberish;
    collateral: BigNumberish;
  };

  export type DealTimeoutStructOutput = [
    timeout: bigint,
    collateral: bigint
  ] & { timeout: bigint; collateral: bigint };

  export type DealTimeoutsStruct = {
    agree: SharedStructs.DealTimeoutStruct;
    submitResults: SharedStructs.DealTimeoutStruct;
    judgeResults: SharedStructs.DealTimeoutStruct;
    mediateResults: SharedStructs.DealTimeoutStruct;
  };

  export type DealTimeoutsStructOutput = [
    agree: SharedStructs.DealTimeoutStructOutput,
    submitResults: SharedStructs.DealTimeoutStructOutput,
    judgeResults: SharedStructs.DealTimeoutStructOutput,
    mediateResults: SharedStructs.DealTimeoutStructOutput
  ] & {
    agree: SharedStructs.DealTimeoutStructOutput;
    submitResults: SharedStructs.DealTimeoutStructOutput;
    judgeResults: SharedStructs.DealTimeoutStructOutput;
    mediateResults: SharedStructs.DealTimeoutStructOutput;
  };

  export type DealPricingStruct = {
    instructionPrice: BigNumberish;
    paymentCollateral: BigNumberish;
    resultsCollateralMultiple: BigNumberish;
    mediationFee: BigNumberish;
  };

  export type DealPricingStructOutput = [
    instructionPrice: bigint,
    paymentCollateral: bigint,
    resultsCollateralMultiple: bigint,
    mediationFee: bigint
  ] & {
    instructionPrice: bigint;
    paymentCollateral: bigint;
    resultsCollateralMultiple: bigint;
    mediationFee: bigint;
  };

  export type DealStruct = {
    dealId: string;
    members: SharedStructs.DealMembersStruct;
    timeouts: SharedStructs.DealTimeoutsStruct;
    pricing: SharedStructs.DealPricingStruct;
  };

  export type DealStructOutput = [
    dealId: string,
    members: SharedStructs.DealMembersStructOutput,
    timeouts: SharedStructs.DealTimeoutsStructOutput,
    pricing: SharedStructs.DealPricingStructOutput
  ] & {
    dealId: string;
    members: SharedStructs.DealMembersStructOutput;
    timeouts: SharedStructs.DealTimeoutsStructOutput;
    pricing: SharedStructs.DealPricingStructOutput;
  };
}

export interface IHiveMediationHandlerInterface extends Interface {
  getFunction(nameOrSignature: "mediationRequest"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "mediationRequest",
    values: [SharedStructs.DealStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "mediationRequest",
    data: BytesLike
  ): Result;
}

export interface IHiveMediationHandler extends BaseContract {
  connect(runner?: ContractRunner | null): IHiveMediationHandler;
  waitForDeployment(): Promise<this>;

  interface: IHiveMediationHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  mediationRequest: TypedContractMethod<
    [deal: SharedStructs.DealStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "mediationRequest"
  ): TypedContractMethod<
    [deal: SharedStructs.DealStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
